#version: "3"

services:
  db:
    image: mariadb:10.6
    container_name: drupal-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: drupal:10
    user: "1000:1000"
    container_name: drupal-php
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html


  pma:
    image: phpmyadmin/phpmyadmin
    container_name: drupal-pma
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data:
  drupal_data:
